<?php 

define('BOT_TOKEN', 'BOTOKEN:HERE111');


function getRandomGame() {
	
$keys = file('steam.txt', FILE_IGNORE_NEW_LINES);

$key = $keys[mt_rand(0, sizeof($keys) - 1)]; 	
	
	return $key;
}


$content = file_get_contents("php://input");
$update = json_decode($content, true);
if (!$update)
{
	$chat	= '@BotTestGrp';
	file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?parse_mode=html&chat_id='.$chat.'&text='.urlencode("<b> Empty Request Recieved HTTP STATUS CHECKER BOT</b>"));//DEBUG
	exit;
}


if (isset($update["message"]))
{
	
$chat = $update["message"]['chat']['id'];
$user = $update["message"]['from']['id']; 
$fname = $update["message"]['from']['first_name'];
$mid = $update["message"]['message_id'];
$message = $update["message"]['text'];
	
file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?chat_id='.$chat.'&text='.urlencode($result).'&reply_to_message_id='.$mid.'&parse_mode=Markdown');
}


if ($message=='/about@SteamGenbot'||$message=='/about')
			{
			$AnswerText	= "*🤜  ABOUT ME  🤛*

*🕶 Name:*_ Steam Key Generator 🔑_
*💢 Type:*_ BOT 🕹_ 

*✅ Descriptions:* _SteamGenBot is a bot which helps you to get steam keys for free without paying a cent with Game._

*🛠 Version:*  _1.0_ 

🙍🏻‍♂️ *Developer: CardersKing*
💌  *Username:* @CardersKing
☎️ *Phone:*  0xxxxxxxxx (Guess the left 😂) 

😎 *Made with 💀 in  ☠️ Global Carding Inc. ☠️*

*👉🏾  Send*  /help * to get a bit help on how to use me.* 
 *Enjoy 😉*";
			file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?chat_id='.$chat.'&text='.urlencode($AnswerText).'&reply_to_message_id='.$mid.'&parse_mode=Markdown');
	
			}
			
if ($message=='/channel@SteamGenbot'||$message=='/channel')
			{
			$AnswerText	= "*🤜  ABOUT My Developer's Channel  🤛*

*🕶 Name:*_  Global Carding Inc. 🔑 _

🙍🏻‍♂️ *Developer: CardersKing*
💌  *Username:* @CardersKing
🙄🙄 *Channel:* https://t.me/joinchat/AAAAAEeNaW3Z-MVhWno9cA 
😎 *Made with 💀 in  ☠️ Global Carding Inc. ☠️*

*👉🏾  Send*  /help * to get a bit help on how to use me.* 
 *Enjoy 😉*";
			file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?chat_id='.$chat.'&text='.urlencode($AnswerText).'&reply_to_message_id='.$mid.'&parse_mode=Markdown');
	
			}
			

			
		if ($message=='/start@SteamGenbot'|| $message=='/start')
			{
			$AnswerText	= "Hi! <b> $fname, </b>
<em> I am a bot which can help to get steam keys with game :) </em> 
 
👉🏾 <b> Send </b> /help <b> to get a bit help on how to use me </b>

👉🏾 <b> Send </b> /about <b> to know about me and my developer </b>

👉🏾 <b> Send </b> /channel <b> to get the private link of developer's channel </b>
Enjoy 😉";
	        $text = urlencode($AnswerText);
	
			file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?chat_id='.$chat.'&text='.$text.'&reply_to_message_id'.$id.'&parse_mode=html');
			}
			
			
		if ($message=='/help@SteamGenbot'||$message=='/help')
			{
			$AnswerText	= "Hi! $fname, 
     <b> How to use Me? </b> 
 
 <code>
1. Send /random
2. I will check in my database and get you random game with its Key.
 </code>
 
👉🏾 <b> Send </b> /commands <b> to get all list of the commands </b>

Enjoy 😉";
	$text = urlencode($AnswerText);
	
			file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?chat_id='.$chat.'&text='.$text.'&parse_mode=html');
}


		if ($message=='/commands@SteamGenbot'||$message=='/commands')
			{
			$AnswerText	= "Hi! $fname, 
     <b> Commands List </b> 
<code>1. /start 
2. /random
3. /help
4. /about
5. /commands
6. /channel</code>
 
👉🏾 <b> Don't Forget to Join Our Channel, send</b> /channel <b> to get the private link of the channel :D </b>

Enjoy 😉";
	$text = urlencode($AnswerText);
	
			file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?chat_id='.$chat.'&text='.$text.'&parse_mode=html');
}




  if ($message=='/random@SteamGenbot'||$message=='/random')
{

$game = getRandomGame();

$AnswerText = " <b>👽 Results 👽 </b>
<b> ------------------------------- </b>
$game                
<b> ------------------------------- </b>
<code>Generated by @SteamGenbot</code>

Powered by <b> Global Carding Inc. </b>
";

		
$text = urlencode($AnswerText);

file_get_contents('https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?chat_id='.$chat.'&text='.$text.'&parse_mode=html');
}


if ($message !== '/help@SteamGenbot' || $message !== '/help' || $message!== '/start' || $message !== '/start@SteamGenbot' || $message !== '/about' || $message !== '/about@SteamGenbot' || $message !=='/random' || $message !== '/random@SteamGenbot') {

$AnswerText	= "Hi! $fname, 
     <b> Unkown Command </b> 
 
 <code>
1. Send /random
2. I will check my database and send you random game.
 </code>

👉 <b> Send </b> /about <b> to know about me and my developers ✌ </b>

Enjoy 😉";
	$text = urlencode($AnswerText);
	

	
}

?>